import { PGListing } from '../types';

export const INITIAL_PGS: PGListing[] = [
  { 
    id: '1', 
    name: 'Shivalik Home PG', 
    area: 'Navrangpura', 
    address: '12, Shivalik Society, Near CG Road, Navrangpura, Ahmedabad, Gujarat 380009',
    rent: 8500, 
    deposit: 15000,
    type: 'Boys', 
    foodAvailable: true, 
    verified: true, 
    imageUrls: ['https://picsum.photos/seed/pg1/800/600', 'https://picsum.photos/seed/pg1b/800/600', 'https://picsum.photos/seed/pg1c/800/600'],
    availableBeds: 2,
    facilities: ['WiFi', 'AC', 'Laundry', 'Food Included', 'Housekeeping', 'RO Water'],
    description: 'Premium Boys PG located in the heart of Navrangpura. Walking distance to major coaching institutes and CG Road. Delicious home-cooked Punjabi & Gujarati thali available.',
    rules: 'No smoking. No alcohol. Friends are allowed only till 8 PM in the common area.',
    curfew: '11:00 PM',
    ownerName: 'Rahul Patel',
    mobileNumber: '+91 9876543210',
    whatsappNumber: '+91 9876543210',
    availabilityState: 'Few Beds Left',
    lastUpdated: '2 days ago',
    totalViews: 1240,
    rating: 4.8,
    reviewCount: 34
  },
  { 
    id: '2', 
    name: 'Krishna Girls Hostel', 
    area: 'Vastrapur', 
    address: 'Sunrise Park Road, Near Vastrapur Lake, Ahmedabad, Gujarat 380015',
    rent: 9000, 
    deposit: 18000,
    type: 'Girls', 
    foodAvailable: true, 
    verified: true, 
    imageUrls: ['https://picsum.photos/seed/pg2/800/600', 'https://picsum.photos/seed/pg2b/800/600', 'https://picsum.photos/seed/pg2c/800/600'],
    availableBeds: 0,
    facilities: ['WiFi', 'AC', 'Laundry', 'Food Included', 'Housekeeping', 'CCTV', 'Attached Bathroom'],
    description: 'Safe and secure girls accommodation near IIM Ahmedabad and Vastrapur Lake. High-speed WiFi and Biometric entry.',
    rules: 'Strictly for students and working professionals. No late nights without prior permission.',
    curfew: '10:00 PM',
    ownerName: 'Meena Shah',
    mobileNumber: '+91 9876543211',
    whatsappNumber: '+91 9876543211',
    availabilityState: 'Full',
    lastUpdated: '1 week ago',
    totalViews: 2100,
    rating: 4.6,
    reviewCount: 52
  },
  { 
    id: '3', 
    name: 'Comfort Stay PG', 
    area: 'SG Highway', 
    address: 'B-201, Titanium Heights, SG Highway, Ahmedabad',
    rent: 7500, 
    deposit: 10000,
    type: 'Boys', 
    foodAvailable: false, 
    verified: false, 
    imageUrls: ['https://picsum.photos/seed/pg3/800/600'],
    availableBeds: 5,
    facilities: ['WiFi', 'Parking', 'RO Water', 'Attached Bathroom'],
    description: 'Affordable stay for boys. Very close to SG Highway corporates. Lots of nearby tiffin services available.',
    rules: 'Maintain cleanliness. Pay rent by 5th of every month.',
    curfew: 'No Strict Curfew',
    ownerName: 'Amit Desai',
    mobileNumber: '+91 9876543212',
    whatsappNumber: '+91 9876543212',
    availabilityState: 'Available',
    lastUpdated: '3 days ago',
    totalViews: 856,
    rating: 3.9,
    reviewCount: 12
  },
  { 
    id: '4', 
    name: 'Aakash PG & Co-living', 
    area: 'Satellite', 
    address: 'Shivranjani Cross Roads, Satellite, Ahmedabad',
    rent: 11000, 
    deposit: 22000,
    type: 'Co-ed', 
    foodAvailable: true, 
    verified: true, 
    imageUrls: ['https://picsum.photos/seed/pg4/800/600', 'https://picsum.photos/seed/pg4b/800/600'],
    availableBeds: 8,
    facilities: ['WiFi', 'AC', 'Laundry', 'Food Included', 'Parking', 'Power Backup', 'Housekeeping', 'CCTV'],
    description: 'Modern luxury co-living space designed for the modern professional. Dedicated work areas, gym, and recreation room.',
    rules: 'Respect co-residents. Clean up after using common kitchen.',
    curfew: '12:00 AM',
    ownerName: 'Priya Joshi',
    mobileNumber: '+91 9876543213',
    whatsappNumber: '+91 9876543213',
    availabilityState: 'Available',
    lastUpdated: '1 day ago',
    totalViews: 3450,
    rating: 4.9,
    reviewCount: 88
  },
];
